# -*- ispell-change-dictionary: english; -*-
#+TITLE: Tattoos
#+AUTHOR: innoxia, bicobus

For a version without all of the comments, see "rental_daddy.xml".

* coreAttributes

** value

The base value of this tattoo. All of the standard tattoos are 500 flames. I
roughly base things on 1 flame = 10p, so 10 flames = £1.

#+BEGIN_SRC xml
<value>2000</value> 
#+END_SRC

** name

The name of this tattoo.

#+BEGIN_SRC xml
<name><![CDATA[heart womb]]></name>
#+END_SRC

** description

The description that's shown in tooltips and on the item's inspection page.

#+BEGIN_SRC xml
<description><![CDATA[A stylised heart tattoo, which roughly resembles the shape of a female's reproductive system.]]></description>
#+END_SRC

** availabilityRequirements

Availability requirements for this tattoo. Use 'npc' for the character receiving
the tattoo. Can be left blank.

+ Example of tattoo available only to the player or feminine NPCs ::
  #+BEGIN_SRC xml
  <availabilityRequirements><![CDATA[npc.isPlayer() || npc.isFeminine()]]></availabilityRequirements>
  #+END_SRC

** imageName

The file path for this clothing's image. All images MUST BE .svg format. Colours
to be used are described below, above the 'primaryColours' element. I use the
free program 'InkScape' to make my .svg images.

.svg images scale perfectly up and down to any size, so, while it should be a
square, it doesn't really matter what size your canvas is (although I use
256 \times 256 as a personal preference).

#+BEGIN_SRC xml
<imageName>heart_womb.svg</imageName>
#+END_SRC

** enchantmentLimit

How many enchantments can be fit into this item. I feel like 5 is a good number
for this.

#+BEGIN_SRC xml
<enchantmentLimit>10</enchantmentLimit>
#+END_SRC

** slotAvailability

Inventory slots that this tattoo can be assigned to. Leave blank to allow all
slots to be used. Possible slots are found here:
https://github.com/Innoxia/liliths-throne-public/blob/master/src/com/lilithsthrone/game/inventory/InventorySlot.java

#+BEGIN_SRC xml
<slotAvailability>
	<slot>GROIN</slot>
</slotAvailability>
#+END_SRC

** colours

Please consult the relevant [[file:index.org::#colours][documentation]] about colours.

Use this section to define available colours for your tattoo. The game detects
specific colour values, and recolours them to the value chosen by the player.

#+BEGIN_SRC xml
<primaryColours values="ALL"/>
<secondaryColours values="ALL"/>
<tertiaryColours values="ALL"/>
#+END_SRC

You can also make your own, custom list of colours to be used. If you want to include custom colours, do not define a 'values' attribute, and instead, list each Colour, like in the example below.

#+BEGIN_SRC xml
<tertiaryColours>
	<colour>CLOTHING_PINK</colour>
	<colour>CLOTHING_PINK_LIGHT</colour>
</tertiaryColours>
#+END_SRC
